name: cc_001
description: "SimpleTicket â€” A Flutter ticketing app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.2.2

  # State management & routing
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1

  # QR
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2

  # Utilities
  uuid: ^4.5.1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
